### ISSUE TITLE
Battle.net update broke this

### ISSUE THREAD

**Issue by mijofa** [dafzor/bnetlauncher#22] opened 2018-06-24 02:49 UTC
Battle.net auto-updated to Build 10202 on 2018/06/22 and since then I haven't been able to make bnetlauncher work with Overwatch. I don't have any other Battle.net games installed so I'm not sure if it's actually affected any other games.
I'm runninng the latest version of bnetlauncher, I was running an older version, but updated when I ahd this problem and the problem is still occuring. I've attached the debug log below.

[debug_20180624_1245058048.log](https://github.com/dafzor/bnetlauncher/files/2130427/debug_20180624_1245058048.log)

**Comment by raymondafcripps** [comment] 2018-06-24 05:48
I can confirm that it's not just Overwatch. I get the same error for all of my installed Battle.net games (Overwatch and Destiny 2) on both my Desktop and Laptop with bnetlauncher v119

**Comment by mijofa** [comment] 2018-06-24 06:28
Looks like Battle.net doesn't support the "battlenet://" URI handler the same way anymore. I tried launching "battlenet://Pro" from the run dialog and all it did was open Battle.net to the Overwatch tab without launching the game. "battlenet://S2" switched to the Starcraft tab, so it's definitely triggering something in Battle.net, even though it's not launching the game itself

In battle.net logs I get this after I dispatch the URI handler:
> D 2018-06-24 06:49:42.092167 [CommandQueue] {Main} Received IPC Message: IPC_COMMAND
> I 2018-06-24 06:49:42.092207 [CommandQueue] {Main} Dispatching Command: handle_uri battlenet://Pro
> I 2018-06-24 06:49:42.092242 [ScreenController] {Main} Changing screen to: Games
> D 2018-06-24 06:49:42.092377 [GameController] {Main} Selecting game family by id: Pro
> I 2018-06-24 06:49:42.094897 [GameController] {Main} Picked default selection by type for family: Pro lastSelectedAccountName= lastRegion=US lastTypeString=retail regionHint=US foundAccount=GameAccount(ai=[5272175-Pro(retail) r:?? entity:(Game: US-Pro-117784626) 05213C78[G]] region=US name= visible=1 uniqueId=Pro_retail) foundRegionOverride=US

**Comment by dafzor** [comment] 2018-06-24 09:28
I had already confirmed on issue #19 battle.net client no longer launches the game when using battlenet:// shortcuts.

I don't expect blizzard to fix it anymore so i'll try to find workaround, ~~but it's going to take some time~~. Seems I may have found a quick and dirty way to work around it, you find a [rough early beta here](https://madalien.com/pub/bnetlauncher/bnetlauncher_v120b1.zip).

**Comment by MoKiChU** [comment] 2018-06-24 11:21
Hi dafzor,

It's perfect, I just tested 1.20b1 version, and it's perfect, the only difference compared to before is that the window of Battle.net appears briefly (but it is not at all annoying).

Thank you very much !

**Comment by mijofa** [comment] 2018-06-24 11:24
Works great! Thanks. 👍
This actually works better for me than before as it previously didn't work if Battle.net was minimised in the tray, now it correctly brings Battle.net to the foreground and then launches the requested game

**Comment by dafzor** [comment] 2018-06-24 12:17
[Improved version](https://madalien.com/pub/bnetlauncher/bnetlauncher_v120b2.zip), if nobody reports any issue it will become the new release.

**Comment by ghost** [comment] 2018-06-24 12:39
Now that the launching method is different, can we hope to create a shortcut for PTRs (Overwatch PTR for example) ? Or nothing has changed on this subject and it remains impossible ?

Thank you in advance.

**Comment by dafzor** [comment] 2018-06-24 12:56
It's was never impossible, just a pain to implement.
The only way I see to do it at the moment would be to just blinding send a click event into the window to hit the combo box to give it focus then use send arrow key keystrokes to change the selection.

This is a very hacky method which would break on any minor change to the blizzard client or if the user did anything during that process, that's why I've chosen not to do it as it more work then it's worth.

**Comment by ghost** [comment] 2018-06-24 13:02
Thank you for the clarification !

**Comment by Ethan-BB** [comment] 2018-06-24 21:19
Firstly, thanks Blizz for breaking stuff :D

Now to meaty stuff, I did some digging, and pulled new strings battle.net uses to launch games (and some windows)

All commands are now against "Battle.net.exe"

Commands (all are case sensitive):
```
--exec="launch DST2"		Launches Destiny 2
--exec="launch WoW"		Launches WoW
--exec="launch VIPR"		Launches CoD: Black Ops 4 (probably, not out yet)
--exec="launch D3"		Launches Diablo 3
--exec="launch S1"		Launches Starcraft Remastered
--exec="launch S2"		Launches Starcraft 2
--exec="launch WTCG"		Launches Hearthstone
--exec="launch Hero"		Launches HOTS (not tested)
--exec="launch Pro"		Launches Overwatch
--exec="focus play"		Opens or switches to Game tab
--exec="focus shop"		Opens or switches to Shop tab
--exec="focus social"		Opens or switches to Social tab
--exec="focus news"		Opens or switches to News tab
--exec="dialog friends"		Opens Friends window
--exec="dialog settings"	Opens Launcher and goes to Settings window
```

With this known, I hope bnetlauncher will be fixed in no-time (or at least SOON™).

Edit: Looks like 1.20 beta is already done ... well, at least commands are now public, and someone will maybe want command for friend window :P

Edit 2: Beta 2 is sadly not working for me, I have friends window always open, and looks like ENTER is being send there instead of Launcher window which opens second later, but it works fine with friends list closed.
However I would like to recommend commands above if possible ;-)
They are used in JumpLists and are native.

**Comment by MoKiChU** [comment] 2018-06-24 23:06
Thank you for this informations Ethan-BB ;)

**Comment by dafzor** [comment] 2018-06-25 07:40
@Ethan-BB thanks for the detective work, i'll redo the beta using your method since it's a lot less hacky.

**Comment by MoKiChU** [comment] 2018-06-25 10:39
Thank you @dafzor,

We look forward to the release 1.20b3 version.

**Comment by dafzor** [comment] 2018-06-25 12:58
Super rush job so had zero testing [121b1](https://madalien.com/pub/bnetlauncher/bnetlauncher_v121b1.zip).

**Comment by Ethan-BB** [comment] 2018-06-25 13:38
WoW, D3, Destiny 2, HS, SC2 and OW works fine.
SC Remastered just opens the launcher ... gonna guess typo/wrong letter case?

**Comment by dafzor** [comment] 2018-06-25 13:42
Forgot to update sc1 since it's the only one that changed, will do it as soon as I can.

**Comment by ghost** [comment] 2018-06-25 14:43
Is it possible to add support for CoD: BO4 in advance ?

--exec="launch VIPR"		Launches CoD: Black Ops 4

**Comment by Ethan-BB** [comment] 2018-06-25 14:46
It's already added (at least in beta) with codbo4 flag.
![image](https://user-images.githubusercontent.com/12885129/41857228-4b56029e-7897-11e8-9089-84d41a5b3f4a.png)

**Comment by MoKiChU** [comment] 2018-06-25 14:47
Thank you !

**Comment by dafzor** [comment] 2018-06-25 18:29
Hope this is the [last beta needed](https://madalien.com/pub/bnetlauncher/bnetlauncher_v121b3.zip). Everything should work, tested on regular and beta client with the games I had installed (overwatch, wow, diablo).

After thinking about it, pushed beta into release since it should be better then totally broken tool. Release is just beta 3 renamed.

**Comment by ghost** [comment] 2018-06-25 20:00
Thank you @dafzor ! It's perfect !

**Closed as completed** 2018-06-25 20:18 UTC

**Comment by BNK3R-Boy** [comment] 2018-06-26 13:42
<strike>I tried this on normal and beta launcher and it dont work at all. Maybe only a problem in europe.</strike>

got it! 
Battle.net.exe --exec="launch S2"  <-- works now

Launcher must already be loaded otherwise the game does not start and it ends in the launcher.

**Comment by MoKiChU** [comment] 2018-06-26 13:46
I am in Europe (France), no problem for me.

**Comment by mijofa** [comment] 2018-07-12 09:55
Just in case anyone's interested. Turns out I can use the 121b1 version to play PTR, I just gotta be real quick about selecting the PTR version before it manages to press enter

**Comment by concatime** [comment] 2019-05-22 22:00
@Ethan-BB How did you get that window?

**Comment by dafzor** [comment] 2019-05-22 22:04
> @Ethan-BB How did you get that window?

Just double clicking bnetlauncher.exe will show it. Information is also available in a more readable form in the [README.md](https://github.com/dafzor/bnetlauncher/blob/master/README.md)

**Comment by concatime** [comment] 2019-05-22 22:39
Oh man, I tough it was from Battlet.net.exe. Perfect.

**Comment by prestonpeterson** [comment] 2019-08-24 22:04
@Ethan-BB Classic WoW is upon us now! How did you retrieve the list of game codes before? I'm trying to figure out what the code for classic is. The obvious ones like WoWC and CWoW aren't working :(

**Comment by dafzor** [comment] 2019-08-24 22:19
I doubt a valid WoW Classic code would exist since it's setup as a sub-game like the ptr.

That said, have you give the [latest beta](https://github.com/dafzor/bnetlauncher/releases/tag/v2.05) a try?

**Comment by lucasvienna** [comment] 2019-09-16 17:44
> 
> 
> I doubt a valid WoW Classic code would exist since it's setup as a sub-game like the ptr.
> 
> That said, have you give the [latest beta](https://github.com/dafzor/bnetlauncher/releases/tag/v2.05) a try?

Beta is working perfectly for me. 

Would still be nice to know what the product code is, or if it is possible at all to launch PTR-style games. If anyone figures it out, please share :)

**Comment by lijinhui123** [comment] 2022-07-27 02:42
> 首先，感谢暴雪打破了东西：D
> 
> 现在到肉肉的东西，我做了一些挖掘，并拉出了战网用来启动游戏（和一些窗口）的新字符串
> 
> 现在所有命令都针对“Battle.net.exe”
> 
> 命令（都区分大小写）：
> 
> ```
> --exec="launch DST2"		Launches Destiny 2
> --exec="launch WoW"		Launches WoW
> --exec="launch VIPR"		Launches CoD: Black Ops 4 (probably, not out yet)
> --exec="launch D3"		Launches Diablo 3
> --exec="launch S1"		Launches Starcraft Remastered
> --exec="launch S2"		Launches Starcraft 2
> --exec="launch WTCG"		Launches Hearthstone
> --exec="launch Hero"		Launches HOTS (not tested)
> --exec="launch Pro"		Launches Overwatch
> --exec="focus play"		Opens or switches to Game tab
> --exec="focus shop"		Opens or switches to Shop tab
> --exec="focus social"		Opens or switches to Social tab
> --exec="focus news"		Opens or switches to News tab
> --exec="dialog friends"		Opens Friends window
> --exec="dialog settings"	Opens Launcher and goes to Settings window
> ```
> 
> 知道了这一点，我希望 bnetlauncher 能很快得到修复（或至少很快）。
> 
> 编辑：看起来 1.20 beta 已经完成......好吧，至少命令现在是公开的，有人可能会想要朋友窗口的命令：P
> 
> 编辑 2：遗憾的是，Beta 2 对我不起作用，我的朋友窗口总是打开，看起来像 ENTER 被发送到那里，而不是稍后打开的 Launcher 窗口，但它在朋友列表关闭的情况下工作正常。 但是，如果可能的话，我想推荐上面的命令；-) 它们在 JumpLists 中使用并且是本机的。

**Comment by brunofin** [comment] 2022-09-16 18:06
hello, did anyone figure out the classic launch code? thanks
