### ISSUE TITLE
WoW Classic TBC

### ISSUE THREAD

**Issue by SilverSaw** [dafzor/bnetlauncher#56] opened 2021-05-19 20:27 UTC
Classic TBC can not be opened, tested with the latest 2.15exp

**Comment by dafzor** [comment] 2021-05-19 20:56
Has stated in issue #37 currently it's unlikely i'll properly re-implement that feature, that said i did a quick test and couldn't reproduce the issue (launched the game with no failure).

**Comment by ShizCalev** [comment] 2021-05-19 22:14
Having the same issue - that said, the experimental version in #37 works perfectly.

**Comment by SilverSaw** [comment] 2021-05-20 07:58
Ok i found my issue, the shortcut is working for WoWClassic only if i add the game in Steam Library. Usnig bnetlauncher_v215experimental version of the app.

I am unable to run wowclassic from desktop shortcut like before. My shortcut properties are as following: 
"Target" properties - E:\Launchers\Battle.net\bnetlauncher_v215\bnetlauncher.exe wowclassic
"Start in" properties - E:\Launchers\Battle.net\bnetlauncher_v215

I am not using steam and i would like to have single icon of wowclassic skipping bnetlauncher on my desktop like before.
Where is my mistake ?

**Comment by SilverSaw** [comment] 2021-05-20 08:02
Also to mention that i was using this .bat to clear my cache folder on every startup. Was working like a charm during whole wowclassic exp last 2 years. 
```
rmdir /s /q "E:\World of Warcraft\_classic_\Cache"
start /wait E:\Launchers\Battle.net\bnetlauncher_v214\bnetlauncher.exe wowclassic
```

I was using also HstartUI app to hide console.

**Comment by SilverSaw** [comment] 2021-05-21 19:52
Ok my bad it seems like i had a mistake in my shortcut "Target" properties i tried a couple of times again today and now it is working, using bnetlauncher_v215experimental

**Comment by SilverSaw** [comment] 2021-05-21 19:58
Okay i am reopening this again, because it seems like it is working first time and then it is broken somehow. I still can not simulate, what is wrong and why it become broken after first opening.

**Comment by SilverSaw** [comment] 2021-05-21 20:26
I found it:

When it is not working:
1. Open your Battlenet launcher
2. Minimize it in your system tray or minimize it in the start menu, the result is same.
3. Open bnetlauncher_v215experimental with configured shortcut for wowclassic
4. Battlenet Launcher opens without any action, then after a while giving the error "Game not Found. Retry?"

When it is working:
1. If your Battlenet launcher is not opened at all, not minimized or in the background.
2. If your Battlenet launcher is opened, but in the background. With other words, if the battlenet launcher User Interface is visible for you on the screen (it is opened, but not minimized in system tray or start menu) then shortcut is working again.

It seems like minimizing of the original launcher is causing the issue.

**Comment by dafzor** [comment] 2021-10-04 15:13
The experimental method looks for the battle.net client processes to take a "screenshot" of the window to find the button, it seems it's failing to pick the correct process/window thus not finding the button to click and launching the game.

As previously mentioned, I no longer play any Activision Blizzard games and am not inclined to commit to fully fiz the experimental implementation myself.

**Comment by dafzor** [comment] 2021-10-04 15:14
Closing this as duplicate of #37 to keep discussion concentrated in single issue.

**Closed as completed by dafzor** 2021-10-04 15:14 UTC
Labels: duplicate
