### ISSUE TITLE
Error: Error: Game not found

### ISSUE THREAD

**Issue by scarrken** [dafzor/bnetlauncher#21] opened 2018-06-23 18:11 UTC
Bnetlauncher is set to ow (launching overwatch) It's been working fine, until today. It pops up an error:
![captura de pantalla 73](https://user-images.githubusercontent.com/37123129/41812347-387cca62-76ef-11e8-92ad-1e335767b5fc.png)

It says to check if battle.net can launch the game normally, which is the case.

**Comment by scarrken** [comment] 2018-06-23 18:45
It fixed itself on restart

lol

**Comment by dafzor** [comment] 2018-06-23 18:55
Blizzard has broke launching trough URI (again)... 😞

**Comment by scarrken** [comment] 2018-08-24 18:01
It started happening again, along with a slew of many other issues, like the steam overlay refusing to work with overwatch, and popping up an error at a random time, forcing me out of the game

**Comment by dafzor** [comment] 2018-08-24 19:07
Can you enable debug log (see instructions.txt) and post it here?

**Comment by scarrken** [comment] 2018-08-27 19:27
It fixed itself after a full restart. I'm certain it will rear its ugly face again, so I'll keep you updated if it does

**Comment by dafzor** [comment] 2018-08-27 19:35
There's not much i can do without understanding what's happening, please post a log of when it happens again please.

**Comment by ScranchNew** [comment] 2018-09-14 21:58
I just came across this same issue. Using bnetlauncher through Steam starts the correct game (I tested with both Starcraft II and Overwatch) but bnetlauncher does not seem to find it. It throws an error message and does not attach the Steam overlay.
I'll try restarting the PC and see if it helps.

![error_game_not_found.png](https://user-images.githubusercontent.com/35395613/45576956-e9ed5980-b879-11e8-854b-99485961dc37.PNG)
[debug_20180914_2349517496.log](https://github.com/dafzor/bnetlauncher/files/2385021/debug_20180914_2349517496.log)
[debug_20180914_2352485477.log](https://github.com/dafzor/bnetlauncher/files/2385022/debug_20180914_2352485477.log)

**Comment by ScranchNew** [comment] 2018-09-14 22:14
I just came across this same issue. Using bnetlauncher through Steam starts the correct game (I tested with both Starcraft II and Overwatch) but bnetlauncher does not seem to find it. It throws an error message and does not attach the Steam overlay.

After restarting the system everything seems to work as it should

![error_game_not_found.png](https://user-images.githubusercontent.com/35395613/45576956-e9ed5980-b879-11e8-854b-99485961dc37.PNG)
[debug_20180914_2349517496.log](https://github.com/dafzor/bnetlauncher/files/2385021/debug_20180914_2349517496.log)
[debug_20180914_2352485477.log](https://github.com/dafzor/bnetlauncher/files/2385022/debug_20180914_2352485477.log)

**Comment by dafzor** [comment] 2018-09-15 01:23
Think I know why this is happening (battle.net client helpers now have the same name as the client). Would you mind running [this early beta](https://madalien.com/pub/bnetlauncher/bnetlauncher_v199b2.zip) and tell me if it has the same issue?

**Comment by ScranchNew** [comment] 2018-09-15 14:15
The new beta seems to work perfectly. But even with the old version, I can't reliably replicate the issue, so I can't tell for sure if the problem is fixed.

Thank you for your fast response.

I tried starting Overwatch once with Battle.net closed:
[debug_20180915_1605164386.log](https://github.com/dafzor/bnetlauncher/files/2385780/debug_20180915_1605164386.log)

and once with Battle.net already open:
[debug_20180915_1608163034.log](https://github.com/dafzor/bnetlauncher/files/2385781/debug_20180915_1608163034.log)

**Comment by scarrken** [comment] 2018-09-21 22:19
The problem has not happened for me since. I won't close however, to keep the conversation going.

**Comment by SystemDisc** [comment] 2018-10-18 22:35
I kept running into this error using bnetlauncher.

I found it easier to skip bnetlauncher entirely, and just use Steam to do what bnetlauncher is doing, directly:
https://www.reddit.com/r/Blackops4/comments/9pe6z5/how_to_launch_black_ops_4_with_steam_adds_support/

There's a list of commands here: https://github.com/dafzor/bnetlauncher/issues/22#issuecomment-399788430

**Comment by dafzor** [comment] 2018-10-19 00:20
> I kept running into this error using bnetlauncher.
> 
> I found it easier to skip bnetlauncher entirely, and just use Steam to do what bnetlauncher is doing, directly:
> https://www.reddit.com/r/Blackops4/comments/9pdxku/launching_black_ops_4_with_the_steam_overlay_and/

That post seems to have been deleted, but it is indeed possible to launch codbo4 directly on steam, it just a bit more clunky which is why I made bnetlauncher.

I should be pushing version 2.00 over the weekend which is a considerable rewrite and hopefully should solve all game not found issues.

**Comment by dafzor** [comment] 2018-10-20 13:27
Version 2.00 is out now with a rewrite of how it detects games, so closing this bug.

**Closed as completed by dafzor** 2018-10-20 13:27 UTC
