### ISSUE TITLE
Cannot launch warzone with bnetlauncher.

### ISSUE THREAD

**Issue by jhilrd** [dafzor/bnetlauncher#59] opened 2021-08-13 20:56 UTC
Launching cold war works fine, but warzone does not launch unless I manually click play in battle.net. I can switch to warzone from bocw but that is slow and requires more loading. 

Log: (Looks fine)

16:44:37.6361|16860|Program.Main:133|INFO|Starting bnetlauncher v2.14.7762.28018
16:44:37.6371|16860|Program.LogSystemInfo:733|INFO|Getting System details:
16:44:37.6381|16860|Program.LogSystemInfo:737|INFO|ENV: Microsoft Windows NT 10.0.19042.0 (4.0.30319.42000), 64bit
16:44:37.7119|16860|Program.LogSystemInfo:803|INFO|OS: Microsoft Windows 10 Home (10.0.19042, 64-bit, 1033)
16:44:37.7129|16860|Program.LogSystemInfo:804|INFO|CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz, RAM: 32768MB
16:44:37.7129|16860|Program.LogSystemInfo:805|INFO|GPU: NVIDIA GeForce RTX 2060 (30.0.14.7141, 4095MB)
16:44:37.7139|16860|Program.LogSystemInfo:806|INFO|HDD: Samsung SSD 860 EVO 500GB, WDC WD40EZRZ-00GXCB0
16:44:37.7208|16860|Program.LoadGameList:594|INFO|Loading gamedb files.
16:44:37.7348|16860|Program.LoadGameList:615|INFO|Loaded internal gamedb with '24' games.
16:44:37.7358|16860|Program.LoadGameList:632|INFO|Known games: '24'.
16:44:37.7358|16860|Program.Main:228|INFO|Given parameter 'codmw2019'.
16:44:37.7368|16860|Program.Main:264|INFO|Using 'battlenet' client.
16:44:37.7368|16860|BnetClient.InstallPath:86|INFO|Client InstallPath:'C:\Program Files (x86)\Battle.net'.
16:44:37.7368|16860|Program.Main:280|INFO|Checking for other bnetlauncher processes using same client
16:44:37.7378|16860|Program.Main:288|INFO|No other bnetlauncher detected
16:44:37.8944|16860|Program.Main:331|INFO|Client already running with pid:'16212'.
16:44:37.8954|16860|Program.Main:350|INFO|Issuing game launch command 'ODIN' at '04:44:37.8944'
16:44:37.8954|16860|BnetClient.InstallPath:86|INFO|Client InstallPath:'C:\Program Files (x86)\Battle.net'.
16:44:38.0700|16860|Processes.GetProcessByNameAfterDate:159|INFO|Searching for process 'ModernWarfare.exe' for '15' seconds.
16:44:38.6292|16860|Processes.GetProcessByNameAfterDate:168|INFO|Found game process started at '04:44:38.5650' with pid:'19680'
16:44:38.6312|16860|Processes.GetProcessStartInfoById:86|INFO|Attempt 1 to find start parameters
16:44:38.7748|16860|Processes.GetProcessStartInfoById:124|INFO|Filename:'C:\Program Files (x86)\Call of Duty Modern Warfare\ModernWarfare.exe'.
16:44:38.7748|16860|Processes.GetProcessStartInfoById:125|INFO|Arguments:' -uid odin'.
16:44:38.7758|16860|Program.Main:428|INFO|Closing game process and starting it under bnetlauncher
16:44:38.8512|16860|Program.Main:488|INFO|Waiting for codmw2019 process 22052 to exit
16:44:51.4112|16860|Program.Main:508|INFO|All operations successful, exiting

*Excuse the horrible video quality but there is a 10 mb size limit

https://user-images.githubusercontent.com/86891625/129417604-b990b1fb-8e66-4b70-93de-b61187f7d787.mp4

**Comment by dafzor** [comment] 2021-08-14 10:21
Hi there, it seems you're starting MW 2019 which no longer works with steam overlay, see #58.

**Comment by dafzor** [comment] 2022-08-05 23:33
Closing as duplicate of #58.

**Closed as not planned by dafzor** 2022-08-05 23:33 UTC
Labels: need more info
